<?php
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the ads table
 *
 * automatically generated by ModelGenerator.php
 */
class Ad extends Model
{
 /**
 * The table associated with the model Ad
 *
 * @var string
 */
    protected $table = 'ads';

    public function getDates()
    {
        return ['start_date', 'end_date'];
    }

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['ad', 'description', 'price', 'site', 'is_active', 'start_date', 'end_date'];

    /**
    * Relationship with the App\Models\Sponsor model.
    *
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */
    public function sponsors()
    {
        return $this->belongsTo('App\Models\Sponsor', 'sponsors_id', 'id');
    }

    /**
    * Relationship with the App\Models\AdTranslation model.
    *
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */
    public function adTranslations()
    {
        return $this->hasMany('App\Models\AdTranslation', 'ads_id', 'id');
    }



}
