<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the addresses table
 *
 * automatically generated by ModelGenerator.php
 */
class Address extends Model {
	/**
	 * The table associated with the model Address
	 *
	 * @var string
	 */
	protected $table = 'addresses';

	/**
	 * Indicates if the model should be timestamped.
	 *
	 * @var bool
	 */
	public $timestamps = false;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['country', 'state', 'town', 'city', 'street', 'interior_number', 'exterior_number', 'zipcode',
		'description'];

	/**
	 * Relationship with the App\Models\CustomerAddress model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function customerAddresses() {
		return $this->hasMany('App\Models\CustomerAddress', 'addresses_id', 'id');
	}

	/**
	 * Relationship with the App\Models\Shipper model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function shippers() {
		return $this->hasMany('App\Models\Shipper', 'addresses_id', 'id');
	}

}
