<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the address_types table
 *
 * automatically generated by ModelGenerator.php
 */
class AddressType extends Model
{
 /**
 * The table associated with the model AddressType
 *
 * @var string
 */
    protected $table = 'address_types';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['is_active'];

    /**
    * Relationship with the App\Models\AddressTypeTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function addressTypeTranslations()
    {
        return $this->hasMany('App\Models\AddressTypeTranslation', 'address_types_id', 'id');
    }

    /**
    * Relationship with the App\Models\CustomerAddress model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function customerAddresses()
    {
        return $this->hasMany('App\Models\CustomerAddress', 'address_types_id', 'id');
    }

}

