<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the ad_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class AdTranslation extends Model
{
 /**
 * The table associated with the model AdTranslation
 *
 * @var string
 */
    protected $table = 'ad_translations';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['image_url'];

    /**
    * Relationship with the App\Models\Ad model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function ads()
    {
        return $this->belongsTo('App\Models\Ad', 'ads_id', 'id');
    }

    /**
    * Relationship with the App\Models\Lang model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function langs()
    {
        return $this->belongsTo('App\Models\Lang', 'langs_id', 'id');
    }

}

