<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the categories_designs table
 *
 * automatically generated by ModelGenerator.php
 */
class CategoriesDesign extends Model
{
 /**
 * The table associated with the model CategoriesDesign
 *
 * @var string
 */
    protected $table = 'categories_designs';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\BaseCategory model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function baseCategories()
    {
        return $this->belongsTo('App\Models\BaseCategory', 'base_categories_id', 'id');
    }

    /**
    * Relationship with the App\Models\Design model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function designs()
    {
        return $this->belongsTo('App\Models\Design', 'designs_id', 'id');
    }

}

