<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the codes table
 *
 * automatically generated by ModelGenerator.php
 */
class Code extends Model
{
 /**
 * The table associated with the model Code
 *
 * @var string
 */
    protected $table = 'codes';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['code', 'start_date', 'end_date', 'activation_token', 'usage_count', 'is_active'];

    /**
    * Relationship with the App\Models\CodesDiscountType model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function codesDiscountTypes()
    {
        return $this->hasMany('App\Models\CodesDiscountType', 'codes_id', 'id');
    }

    /**
    * Relationship with the App\Models\CodesPromotionsType model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function codesPromotionsTypes()
    {
        return $this->hasMany('App\Models\CodesPromotionsType', 'codes_id', 'id');
    }

    /**
    * Relationship with the App\Models\CustomersCode model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function customersCodes()
    {
        return $this->hasMany('App\Models\CustomersCode', 'codes_id', 'id');
    }

    /**
    * Relationship with the App\Models\OrdersCoupon model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function ordersCoupons()
    {
        return $this->hasMany('App\Models\OrdersCoupon', 'codes_id', 'id');
    }

}

