<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the codes_promotions_types table
 *
 * automatically generated by ModelGenerator.php
 */
class CodesPromotionsType extends Model {
	/**
	 * The table associated with the model CodesPromotionsType
	 *
	 * @var string
	 */
	protected $table = 'codes_promotions_types';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['codes_id', 'promotions_types_id'];

	/**
	 * Relationship with the App\Models\Code model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\belongsTo
	 */
	public function codes() {
		return $this->belongsTo('App\Models\Code', 'codes_id', 'id');
	}

	/**
	 * Relationship with the App\Models\PromotionsType model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\belongsTo
	 */
	public function promotionsTypes() {
		return $this->belongsTo('App\Models\PromotionsType', 'promotions_types_id', 'id');
	}

}
