<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the colors table
 *
 * automatically generated by ModelGenerator.php
 */
class Color extends Model {
	/**
	 * The table associated with the model Color
	 *
	 * @var string
	 */
	protected $table = 'colors';

	/**
	 * Indicates if the model should be timestamped.
	 *
	 * @var bool
	 */
	public $timestamps = false;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['hex'];

	/**
	 * Relationship with the App\Models\Cart model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function carts() {
		return $this->hasMany('App\Models\Cart', 'colors_id', 'id');
	}

	/**
	 * Relationship with the App\Models\OrderProduct model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function orderProducts() {
		return $this->hasMany('App\Models\OrderProduct', 'colors_id', 'id');
	}

	/**
	 * Relationship with the App\Models\ProductsColor model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function productsColors() {
		return $this->hasMany('App\Models\ProductsColor', 'colors_id', 'id');
	}

}
