<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the company_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class CompanyTranslation extends Model
{
 /**
 * The table associated with the model CompanyTranslation
 *
 * @var string
 */
    protected $table = 'company_translations';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['company', 'description'];

    /**
    * Relationship with the App\Models\Company model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function companies()
    {
        return $this->belongsTo('App\Models\Company', 'companies_id', 'id');
    }

    /**
    * Relationship with the App\Models\Lang model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function langs()
    {
        return $this->belongsTo('App\Models\Lang', 'langs_id', 'id');
    }

}

