<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the companies table
 *
 * automatically generated by ModelGenerator.php
 */
class Company extends Model
{
 /**
 * The table associated with the model Company
 *
 * @var string
 */
    protected $table = 'companies';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['site_url'];

    /**
    * Relationship with the App\Models\PrivacyPolicy model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function privacyPolicies()
    {
        return $this->belongsTo('App\Models\PrivacyPolicy', 'privacy_policies_id', 'id');
    }

    /**
    * Relationship with the App\Models\TermsCondition model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function termsConditions()
    {
        return $this->belongsTo('App\Models\TermsCondition', 'terms_conditions_id', 'id');
    }

    /**
    * Relationship with the App\Models\CompanySocialMedia model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function companySocialMedia()
    {
        return $this->hasMany('App\Models\CompanySocialMedia', 'companies_id', 'id');
    }

    /**
    * Relationship with the App\Models\CompanyTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function companyTranslations()
    {
        return $this->hasMany('App\Models\CompanyTranslation', 'companies_id', 'id');
    }

}

