<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the company_social_media table
 *
 * automatically generated by ModelGenerator.php
 */
class CompanySocialMedia extends Model
{
 /**
 * The table associated with the model CompanySocialMedia
 *
 * @var string
 */
    protected $table = 'company_social_media';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['url'];

    /**
    * Relationship with the App\Models\Company model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function companies()
    {
        return $this->belongsTo('App\Models\Company', 'companies_id', 'id');
    }

    /**
    * Relationship with the App\Models\ServiceProvider model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function serviceProviders()
    {
        return $this->belongsTo('App\Models\ServiceProvider', 'service_providers_id', 'id');
    }

}

