<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the customer_ratings table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerRating extends Model {
	/**
	 * The table associated with the model CustomerRating
	 *
	 * @var string
	 */
	protected $table = 'customer_ratings';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['customers_id', 'products_id', 'title', 'description', 'rating'];

	/**
	 * Relationship with the App\Models\Customer model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\belongsTo
	 */
	public function customers() {
		return $this->belongsTo('App\Models\Customer', 'customers_id', 'id');
	}

	/**
	 * Relationship with the App\Models\Product model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\belongsTo
	 */
	public function products() {
		return $this->belongsTo('App\Models\Product', 'products_id', 'id');
	}

}
