<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the customer_designs table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerDesign extends Model
{
 /**
 * The table associated with the model CustomerDesign
 *
 * @var string
 */
    protected $table = 'customer_designs';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['is_sellable', 'is_remixable'];

    /**
    * Relationship with the App\Models\Customer model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function customers()
    {
        return $this->belongsTo('App\Models\Customer', 'customers_id', 'id');
    }

    /**
    * Relationship with the App\Models\Product model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function products()
    {
        return $this->belongsTo('App\Models\Product', 'products_id', 'id');
    }

}

