<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the customer_reviews table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomerReview extends Model
{
 /**
 * The table associated with the model CustomerReview
 *
 * @var string
 */
    protected $table = 'customer_reviews';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['title', 'description', 'rating'];

    /**
    * Relationship with the App\Models\Customer model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function customers()
    {
        return $this->belongsTo('App\Models\Customer', 'customers_id', 'id');
    }

    /**
    * Relationship with the App\Models\Order model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function orders()
    {
        return $this->belongsTo('App\Models\Order', 'orders_id', 'id');
    }

}

