<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the customers_codes table
 *
 * automatically generated by ModelGenerator.php
 */
class CustomersCode extends Model {
	/**
	 * The table associated with the model CustomersCode
	 *
	 * @var string
	 */
	protected $table = 'customers_codes';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['codes_id', 'customers_id'];

	/**
	 * Relationship with the App\Models\Code model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\belongsTo
	 */
	public function codes() {
		return $this->belongsTo('App\Models\Code', 'codes_id', 'id');
	}

	/**
	 * Relationship with the App\Models\Customer model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\belongsTo
	 */
	public function customers() {
		return $this->belongsTo('App\Models\Customer', 'customers_id', 'id');
	}

}
