<?php
namespace App\Models;

use App\Traits\S3Trait;
use Illuminate\Database\Eloquent\Model;

/**
 * Eloquent class to describe the designs table
 *
 * automatically generated by ModelGenerator.php
 */
class Design extends Model {
	use S3Trait;
	/**
	 * The table associated with the model Design
	 *
	 * @var string
	 */
	protected $table = 'designs';

	/**
	 * Indicates if the model should be timestamped.
	 *
	 * @var bool
	 */
	public $timestamps = false;

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['design_url', 'nombre', 'ar_preview'];

	protected $appends = [
		'public_image_url',
		'public_gif_url',
	];
	public function getPublicImageUrlAttribute() {
		return $this->temporaryUrl($this->attributes['design_url']);
	}

	public function getPublicGifUrlAttribute() {
		return $this->temporaryUrl($this->attributes['ar_preview']);
	}

	/**
	 * Relationship with the App\Models\CategoriesDesign model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function categoriesDesigns() {
		return $this->hasMany('App\Models\CategoriesDesign', 'designs_id', 'id');
	}

	/**
	 * Relationship with the App\Models\ProductsDesign model.
	 *
	 * @return    Illuminate\Database\Eloquent\Relations\hasMany
	 */
	public function productsDesigns() {
		return $this->hasMany('App\Models\ProductsDesign', 'designs_id', 'id');
	}

}
