<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the discount_types table
 *
 * automatically generated by ModelGenerator.php
 */
class DiscountType extends Model
{
 /**
 * The table associated with the model DiscountType
 *
 * @var string
 */
    protected $table = 'discount_types';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['free_shipping', 'shipping_max_products', 'free_tshirts', 'free_max_products',
        'have_discount', 'discount_amount', 'discount_percent'];

    /**
    * Relationship with the App\Models\CodesDiscountType model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function codesDiscountTypes()
    {
        return $this->hasMany('App\Models\CodesDiscountType', 'discount_types_id', 'id');
    }

    /**
    * Relationship with the App\Models\DiscountTypesTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function discountTypesTranslations()
    {
        return $this->hasMany('App\Models\DiscountTypesTranslation', 'discount_types_id', 'id');
    }

}

