<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the entries table
 *
 * automatically generated by ModelGenerator.php
 */
class Entry extends Model
{
 /**
 * The table associated with the model Entry
 *
 * @var string
 */
    protected $table = 'entries';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\EntryType model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function entryTypes()
    {
        return $this->belongsTo('App\Models\EntryType', 'entry_types_id', 'id');
    }
}

