<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the entry_types table
 *
 * automatically generated by ModelGenerator.php
 */
class EntryType extends Model
{
 /**
 * The table associated with the model EntryType
 *
 * @var string
 */
    protected $table = 'entry_types';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['type'];

    /**
    * Relationship with the App\Models\Entry model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function entries()
    {
        return $this->hasMany('App\Models\Entry', 'entry_types_id', 'id');
    }

}

