<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the faqs table
 *
 * automatically generated by ModelGenerator.php
 */
class Faq extends Model
{
 /**
 * The table associated with the model Faq
 *
 * @var string
 */
    protected $table = 'faqs';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['was_useful', 'is_active'];

    /**
    * Relationship with the App\Models\FaqHasCategory model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function faqHasCategories()
    {
        return $this->hasMany('App\Models\FaqHasCategory', 'faqs_id', 'id');
    }

    /**
    * Relationship with the App\Models\FaqTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function faqTranslations()
    {
        return $this->hasMany('App\Models\FaqTranslation', 'faqs_id', 'id');
    }

}

