<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the faq_categories table
 *
 * automatically generated by ModelGenerator.php
 */
class FaqCategory extends Model
{
 /**
 * The table associated with the model FaqCategory
 *
 * @var string
 */
    protected $table = 'faq_categories';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['is_active'];

    /**
    * Relationship with the App\Models\FaqCategoryTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function faqCategoryTranslations()
    {
        return $this->hasMany('App\Models\FaqCategoryTranslation', 'faq_categories_id', 'id');
    }

    /**
    * Relationship with the App\Models\FaqHasCategory model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function faqHasCategories()
    {
        return $this->hasMany('App\Models\FaqHasCategory', 'faq_categories_id', 'id');
    }

}

