<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the faq_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class FaqTranslation extends Model
{
 /**
 * The table associated with the model FaqTranslation
 *
 * @var string
 */
    protected $table = 'faq_translations';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['question', 'answer'];

    /**
    * Relationship with the App\Models\Faq model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function faqs()
    {
        return $this->belongsTo('App\Models\Faq', 'faqs_id', 'id');
    }

    /**
    * Relationship with the App\Models\Lang model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function langs()
    {
        return $this->belongsTo('App\Models\Lang', 'langs_id', 'id');
    }

}

