<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the fees table
 *
 * automatically generated by ModelGenerator.php
 */
class Fee extends Model
{
 /**
 * The table associated with the model Fee
 *
 * @var string
 */
    protected $table = 'fees';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['base_price', 'is_active'];

    /**
    * Relationship with the App\Models\FeeTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function feeTranslations()
    {
        return $this->hasMany('App\Models\FeeTranslation', 'fees_id', 'id');
    }

    /**
    * Relationship with the App\Models\OrderFee model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function orderFees()
    {
        return $this->hasMany('App\Models\OrderFee', 'fees_id', 'id');
    }

}

