<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the models table
 *
 * automatically generated by ModelGenerator.php
 */
class GiftMessages extends Model
{
    protected $table="gift_messages";
    protected $fillable = ['title', 'message'];
}

