<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the global_prices table
 *
 * automatically generated by ModelGenerator.php
 */
class GlobalPrice extends Model
{
 /**
 * The table associated with the model GlobalPrice
 *
 * @var string
 */
    protected $table = 'global_prices';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['product_price', 'shipping_price'];

    /**
    * Relationship with the App\Models\Lang model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function langs()
    {
        return $this->belongsTo('App\Models\Lang', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\PricesType model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function pricesTypes()
    {
        return $this->belongsTo('App\Models\PricesType', 'prices_types_id', 'id');
    }

}

