<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the invoice_status table
 *
 * automatically generated by ModelGenerator.php
 */
class InvoiceStatus extends Model
{
 /**
 * The table associated with the model InvoiceStatus
 *
 * @var string
 */
    protected $table = 'invoice_status';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['status'];

    /**
    * Relationship with the App\Models\Invoice model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function invoices()
    {
        return $this->hasMany('App\Models\Invoice', 'invoice_status_id', 'id');
    }

}

