<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the langs table
 *
 * automatically generated by ModelGenerator.php
 */
class Lang extends Model
{
 /**
 * The table associated with the model Lang
 *
 * @var string
 */
    protected $table = 'langs';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['language', 'iso_code', 'currency_code', 'currency_symbol', 'units_dimension',
        'units_weight', 'is_active'];

    /**
    * Relationship with the App\Models\AdTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function adTranslations()
    {
        return $this->hasMany('App\Models\AdTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\AddressTypeTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function addressTypeTranslations()
    {
        return $this->hasMany('App\Models\AddressTypeTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\BaseCategoryTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function baseCategoryTranslations()
    {
        return $this->hasMany('App\Models\BaseCategoryTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\CompanyTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function companyTranslations()
    {
        return $this->hasMany('App\Models\CompanyTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\DiscountTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function discountTranslations()
    {
        return $this->hasMany('App\Models\DiscountTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\DiscountTypesTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function discountTypesTranslations()
    {
        return $this->hasMany('App\Models\DiscountTypesTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\FaqCategoryTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function faqCategoryTranslations()
    {
        return $this->hasMany('App\Models\FaqCategoryTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\FaqTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function faqTranslations()
    {
        return $this->hasMany('App\Models\FaqTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\FeeTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function feeTranslations()
    {
        return $this->hasMany('App\Models\FeeTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\GlobalPrice model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function globalPrices()
    {
        return $this->hasMany('App\Models\GlobalPrice', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\OrderStatusTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function orderStatusTranslations()
    {
        return $this->hasMany('App\Models\OrderStatusTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\PaymentMethodTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function paymentMethodTranslations()
    {
        return $this->hasMany('App\Models\PaymentMethodTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\PrivacyPolicyTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function privacyPolicyTranslations()
    {
        return $this->hasMany('App\Models\PrivacyPolicyTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\ProductGenreTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function productGenreTranslations()
    {
        return $this->hasMany('App\Models\ProductGenreTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\ProductStyleTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function productStyleTranslations()
    {
        return $this->hasMany('App\Models\ProductStyleTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\ProductTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function productTranslations()
    {
        return $this->hasMany('App\Models\ProductTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\ProductTypeTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function productTypeTranslations()
    {
        return $this->hasMany('App\Models\ProductTypeTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\PromotionsTypesTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function promotionsTypesTranslations()
    {
        return $this->hasMany('App\Models\PromotionsTypesTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\ShippingEtaTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function shippingEtaTranslations()
    {
        return $this->hasMany('App\Models\ShippingEtaTranslation', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\TermConditionTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function termConditionTranslations()
    {
        return $this->hasMany('App\Models\TermConditionTranslation', 'langs_id', 'id');
    }

}

