<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the log_guides_packages table
 *
 * automatically generated by ModelGenerator.php
 */
class LogGuidesPackage extends Model
{
 /**
 * The table associated with the model LogGuidesPackage
 *
 * @var string
 */
    protected $table = 'log_guides_packages';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\LogGuide model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function logGuides()
    {
        return $this->belongsTo('App\Models\LogGuide', 'log_guides_id', 'id');
    }

    /**
    * Relationship with the App\Models\Package model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function packages()
    {
        return $this->belongsTo('App\Models\Package', 'packages_id', 'id');
    }

}

