<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the log_guides table
 *
 * automatically generated by ModelGenerator.php
 */
class LogGuide extends Model
{
 /**
 * The table associated with the model LogGuide
 *
 * @var string
 */
    protected $table = 'log_guides';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['guide_pdf', 'pieces_per_packages'];

    /**
    * Relationship with the App\Models\User model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function users()
    {
        return $this->belongsTo('App\Models\User', 'users_id', 'id');
    }

    /**
    * Relationship with the App\Models\LogGuidesOrder model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function logGuidesOrders()
    {
        return $this->hasMany('App\Models\LogGuidesOrder', 'log_guides_id', 'id');
    }

    /**
    * Relationship with the App\Models\LogGuidesPackage model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function logGuidesPackages()
    {
        return $this->hasMany('App\Models\LogGuidesPackage', 'log_guides_id', 'id');
    }

}

