<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the log_orders table
 *
 * automatically generated by ModelGenerator.php
 */
class LogOrder extends Model
{
 /**
 * The table associated with the model LogOrder
 *
 * @var string
 */
    protected $table = 'log_orders';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['action'];

    /**
    * Relationship with the App\Models\Order model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function orders()
    {
        return $this->belongsTo('App\Models\Order', 'orders_id', 'id');
    }

    /**
    * Relationship with the App\Models\User model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function users()
    {
        return $this->belongsTo('App\Models\User', 'users_id', 'id');
    }

}

