<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the log_recollections_orders table
 *
 * automatically generated by ModelGenerator.php
 */
class LogRecollectionsOrder extends Model
{
 /**
 * The table associated with the model LogRecollectionsOrder
 *
 * @var string
 */
    protected $table = 'log_recollections_orders';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['was_recollected'];

    /**
    * Relationship with the App\Models\LogRecollection model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function logRecollections()
    {
        return $this->belongsTo('App\Models\LogRecollection', 'log_recollections_id', 'id');
    }

    /**
    * Relationship with the App\Models\Order model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function orders()
    {
        return $this->belongsTo('App\Models\Order', 'orders_id', 'id');
    }

}

