<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the models_categories table
 *
 * automatically generated by ModelGenerator.php
 */
class ModelsCategory extends Model
{
 /**
 * The table associated with the model ModelsCategory
 *
 * @var string
 */
    protected $table = 'models_categories';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\BaseCategory model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function baseCategories()
    {
        return $this->belongsTo('App\Models\BaseCategory', 'base_categories_id', 'id');
    }

    /**
    * Relationship with the App\Models\Model model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function models()
    {
        return $this->belongsTo('App\Models\Model', 'models_id', 'id');
    }

}

