<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the movement_types table
 *
 * automatically generated by ModelGenerator.php
 */
class MovementType extends Model
{
 /**
 * The table associated with the model MovementType
 *
 * @var string
 */
    protected $table = 'movement_types';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['type'];

    /**
    * Relationship with the App\Models\Movement model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function movements()
    {
        return $this->hasMany('App\Models\Movement', 'movement_types_id', 'id');
    }

}

