<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the movements table
 *
 * automatically generated by ModelGenerator.php
 */
class Movement extends Model
{
 /**
 * The table associated with the model Movement
 *
 * @var string
 */
    protected $table = 'movements';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['quantity'];

    /**
    * Relationship with the App\Models\MovementType model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function movementTypes()
    {
        return $this->belongsTo('App\Models\MovementType', 'movement_types_id', 'id');
    }

    /**
    * Relationship with the App\Models\ProductsColor model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function productsColors()
    {
        return $this->belongsTo('App\Models\ProductsColor', 'products_colors_id', 'id');
    }

    /**
    * Relationship with the App\Models\Entry model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function movemententries()
    {
        return $this->hasMany('App\Models\EntryMovement', 'movements_id', 'id');
    }

    /**
    * Relationship with the App\Models\MovementOutlet model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function movementOutlets()
    {
        return $this->hasMany('App\Models\MovementOutlet', 'movements_id', 'id');
    }

}

