<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the order_products table
 *
 * automatically generated by ModelGenerator.php
 */
class OrderProduct extends Model
{
 /**
 * The table associated with the model OrderProduct
 *
 * @var string
 */
    protected $table = 'order_products';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['qty', 'price'];

    /**
    * Relationship with the App\Models\Color model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function colors()
    {
        return $this->belongsTo('App\Models\Color', 'colors_id', 'id');
    }

    /**
    * Relationship with the App\Models\Size model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function sizes()
    {
        return $this->belongsTo('App\Models\Size', 'sizes_id', 'id');
    }

    /**
    * Relationship with the App\Models\Order model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function orders()
    {
        return $this->belongsTo('App\Models\Order', 'orders_id', 'id');
    }

    /**
    * Relationship with the App\Models\Product model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function products()
    {
        return $this->belongsTo('App\Models\Product', 'products_id', 'id');
    }

    /**
    * Relationship with the App\Models\Refund model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function refunds()
    {
        return $this->hasMany('App\Models\Refund', 'order_products_id', 'id');
    }

}

