<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the order_status table
 *
 * automatically generated by ModelGenerator.php
 */
class OrderStatus extends Model
{
 /**
 * The table associated with the model OrderStatus
 *
 * @var string
 */
    protected $table = 'order_status';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\OrderStatusTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function orderStatusTranslations()
    {
        return $this->hasMany('App\Models\OrderStatusTranslation', 'order_status_id', 'id');
    }

    /**
    * Relationship with the App\Models\Order model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function orders()
    {
        return $this->hasMany('App\Models\Order', 'order_status_id', 'id');
    }

}

