<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the order_payments table
 *
 * automatically generated by ModelGenerator.php
 */
class OrderPayment extends Model
{
 /**
 * The table associated with the model OrderPayment
 *
 * @var string
 */
    protected $table = 'order_payments';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\CustomerPayment model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function customerPayments()
    {
        return $this->belongsTo('App\Models\CustomerPayment', 'customer_payments_id', 'id');
    }

    /**
    * Relationship with the App\Models\Order model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function orders()
    {
        return $this->belongsTo('App\Models\Order', 'orders_id', 'id');
    }

}

