<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the order_fees table
 *
 * automatically generated by ModelGenerator.php
 */
class OrderFee extends Model
{
 /**
 * The table associated with the model OrderFee
 *
 * @var string
 */
    protected $table = 'order_fees';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\Fee model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function fees()
    {
        return $this->belongsTo('App\Models\Fee', 'fees_id', 'id');
    }

    /**
    * Relationship with the App\Models\Order model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function orders()
    {
        return $this->belongsTo('App\Models\Order', 'orders_id', 'id');
    }

}

