<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the outlets table
 *
 * automatically generated by ModelGenerator.php
 */
class Outlet extends Model
{
 /**
 * The table associated with the model Outlet
 *
 * @var string
 */
    protected $table = 'outlets';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\OutletsType model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function outletsTypes()
    {
        return $this->belongsTo('App\Models\OutletsType', 'outlets_types_id', 'id');
    }

    /**
    * Relationship with the App\Models\MovementOutlet model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function movementOutlets()
    {
        return $this->hasMany('App\Models\MovementOutlet', 'outlets_id', 'id');
    }

}

