<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the packages table
 *
 * automatically generated by ModelGenerator.php
 */
class Package extends Model
{
 /**
 * The table associated with the model Package
 *
 * @var string
 */
    protected $table = 'packages';
    public $timestamps = true;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['package', 'description', 'min_items', 'max_items', 'width', 'height', 'depth', 'weight','image', 'is_active'];

}

