<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the payment_methods table
 *
 * automatically generated by ModelGenerator.php
 */
class PaymentMethod extends Model
{
 /**
 * The table associated with the model PaymentMethod
 *
 * @var string
 */
    protected $table = 'payment_methods';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['is_active'];

    /**
    * Relationship with the App\Models\CustomerPayment model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function customerPayments()
    {
        return $this->hasMany('App\Models\CustomerPayment', 'payment_methods_id', 'id');
    }

    /**
    * Relationship with the App\Models\Order model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function orders()
    {
        return $this->hasMany('App\Models\Order', 'payment_methods_id', 'id');
    }

    /**
    * Relationship with the App\Models\PaymentMethodTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function paymentMethodTranslations()
    {
        return $this->hasMany('App\Models\PaymentMethodTranslation', 'payment_methods_id', 'id');
    }

}

