<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the payment_sources table
 *
 * automatically generated by ModelGenerator.php
 */
class PaymentSource extends Model
{
 /**
 * The table associated with the model PaymentSource
 *
 * @var string
 */
    protected $table = 'payment_sources';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['conekta_token_id'];

}

