<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the payment_cards table
 *
 * automatically generated by ModelGenerator.php
 */
class PaymentCard extends Model
{
 /**
 * The table associated with the model PaymentCard
 *
 * @var string
 */
    protected $table = 'payment_cards';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['conekta_payment_source_id', 'holder_name', 'brand', 'last_4', 'exp_month', 'exp_year'];

    /**
    * Relationship with the App\Models\CustomerPayment model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function customerPayments()
    {
        return $this->belongsTo('App\Models\CustomerPayment', 'customer_payments_id', 'id');
    }

}

