<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the permissions table
 *
 * automatically generated by ModelGenerator.php
 */
class Permission extends Model
{
 /**
 * The table associated with the model Permission
 *
 * @var string
 */
    protected $table = 'permissions';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['name', 'display_name', 'description', 'is_active'];

    /**
    * Relationship with the App\Models\RolePermission model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function rolePermissions()
    {
        return $this->hasMany('App\Models\RolePermission', 'permissions_id', 'id');
    }

}

