<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the primary_materials table
 *
 * automatically generated by ModelGenerator.php
 */
class PrimaryMaterial extends Model
{
 /**
 * The table associated with the model PrimaryMaterial
 *
 * @var string
 */
    protected $table = 'primary_materials';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['material'];

    /**
    * Relationship with the App\Models\Movement model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function movements()
    {
        return $this->hasMany('App\Models\Movement', 'primary_materials_id', 'id');
    }

}

