<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the privacy_policies table
 *
 * automatically generated by ModelGenerator.php
 */
class PrivacyPolicy extends Model
{
 /**
 * The table associated with the model PrivacyPolicy
 *
 * @var string
 */
    protected $table = 'privacy_policies';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['is_active'];

    /**
    * Relationship with the App\Models\Company model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function companies()
    {
        return $this->hasMany('App\Models\Company', 'privacy_policies_id', 'id');
    }

    /**
    * Relationship with the App\Models\PrivacyPolicyTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function privacyPolicyTranslations()
    {
        return $this->hasMany('App\Models\PrivacyPolicyTranslation', 'privacy_policies_id', 'id');
    }

}

