<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the privacy_policy_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class PrivacyPolicyTranslation extends Model
{
 /**
 * The table associated with the model PrivacyPolicyTranslation
 *
 * @var string
 */
    protected $table = 'privacy_policy_translations';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['privacy_policy'];

    /**
    * Relationship with the App\Models\Lang model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function langs()
    {
        return $this->belongsTo('App\Models\Lang', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\PrivacyPolicy model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function privacyPolicies()
    {
        return $this->belongsTo('App\Models\PrivacyPolicy', 'privacy_policies_id', 'id');
    }

}

