<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the product_styles table
 *
 * automatically generated by ModelGenerator.php
 */
class ProductStyle extends Model
{
 /**
 * The table associated with the model ProductStyle
 *
 * @var string
 */
    protected $table = 'product_styles';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['is_active'];

    /**
    * Relationship with the App\Models\ProductStyleTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function productStyleTranslations()
    {
        return $this->hasMany('App\Models\ProductStyleTranslation', 'product_styles_id', 'id');
    }

    /**
    * Relationship with the App\Models\Product model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function products()
    {
        return $this->hasMany('App\Models\Product', 'product_styles_id', 'id');
    }

    /**
    * Relationship with the App\Models\SizesGuide model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function sizesGuides()
    {
        return $this->hasMany('App\Models\SizesGuide', 'product_styles_id', 'id');
    }

    /**
    * Relationship with the App\Models\StyleResource model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function styleResources()
    {
        return $this->hasMany('App\Models\StyleResource', 'product_styles_id', 'id');
    }

}

