<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the product_categories table
 *
 * automatically generated by ModelGenerator.php
 */
class ProductCategory extends Model
{
 /**
 * The table associated with the model ProductCategory
 *
 * @var string
 */
    protected $table = 'product_categories';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\BaseCategory model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function baseCategories()
    {
        return $this->belongsTo('App\Models\BaseCategory', 'base_categories_id', 'id');
    }

    /**
    * Relationship with the App\Models\Product model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function products()
    {
        return $this->belongsTo('App\Models\Product', 'products_id', 'id');
    }

}

