<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the product_type_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class ProductTypeTranslation extends Model
{
 /**
 * The table associated with the model ProductTypeTranslation
 *
 * @var string
 */
    protected $table = 'product_type_translations';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['type', 'description'];

    /**
    * Relationship with the App\Models\Lang model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function langs()
    {
        return $this->belongsTo('App\Models\Lang', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\ProductType model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function productTypes()
    {
        return $this->belongsTo('App\Models\ProductType', 'product_types_id', 'id');
    }

}

