<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the product_genres table
 *
 * automatically generated by ModelGenerator.php
 */
class ProductGenre extends Model
{
 /**
 * The table associated with the model ProductGenre
 *
 * @var string
 */
    protected $table = 'product_genres';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['is_active'];

    /**
    * Relationship with the App\Models\ProductGenreTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function productGenreTranslations()
    {
        return $this->hasMany('App\Models\ProductGenreTranslation', 'product_genres_id', 'id');
    }

    /**
    * Relationship with the App\Models\Product model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function products()
    {
        return $this->hasMany('App\Models\Product', 'product_genres_id', 'id');
    }

    /**
    * Relationship with the App\Models\SizesGuide model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function sizesGuides()
    {
        return $this->hasMany('App\Models\SizesGuide', 'product_genres_id', 'id');
    }

}

