<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the product_genre_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class ProductGenreTranslation extends Model
{
 /**
 * The table associated with the model ProductGenreTranslation
 *
 * @var string
 */
    protected $table = 'product_genre_translations';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['genre'];

    /**
    * Relationship with the App\Models\Lang model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function langs()
    {
        return $this->belongsTo('App\Models\Lang', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\ProductGenre model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function productGenres()
    {
        return $this->belongsTo('App\Models\ProductGenre', 'product_genres_id', 'id');
    }

}

