<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the promotions_types_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class PromotionsTypesTranslation extends Model
{
 /**
 * The table associated with the model PromotionsTypesTranslation
 *
 * @var string
 */
    protected $table = 'promotions_types_translations';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['type', 'description'];
    public $timestamps = false;
    /**
    * Relationship with the App\Models\Lang model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function langs()
    {
        return $this->belongsTo('App\Models\Lang', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\PromotionsType model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function promotionsTypes()
    {
        return $this->belongsTo('App\Models\PromotionsType', 'promotions_types_id', 'id');
    }

}

