<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the reports table
 *
 * automatically generated by ModelGenerator.php
 */
class Report extends Model
{
 /**
 * The table associated with the model Report
 *
 * @var string
 */
    protected $table = 'reports';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['report', 'decription'];

    /**
    * Relationship with the App\Models\ReportType model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function reportTypes()
    {
        return $this->belongsTo('App\Models\ReportType', 'report_types_id', 'id');
    }

    /**
    * Relationship with the App\Models\StaffReport model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function staffReports()
    {
        return $this->hasMany('App\Models\StaffReport', 'reports_id', 'id');
    }

}

