<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the report_types table
 *
 * automatically generated by ModelGenerator.php
 */
class ReportType extends Model
{
 /**
 * The table associated with the model ReportType
 *
 * @var string
 */
    protected $table = 'report_types';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['type', 'description'];

    /**
    * Relationship with the App\Models\Report model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function reports()
    {
        return $this->hasMany('App\Models\Report', 'report_types_id', 'id');
    }

}

