<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the roles table
 *
 * automatically generated by ModelGenerator.php
 */
class Role extends Model
{
 /**
 * The table associated with the model Role
 *
 * @var string
 */
    protected $table = 'roles';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['name', 'display_name', 'description', 'is_active'];

    /**
    * Relationship with the App\Models\RolePermission model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function rolePermissions()
    {
        return $this->hasMany('App\Models\RolePermission', 'roles_id', 'id');
    }

    /**
    * Relationship with the App\Models\RoleUser model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function roleUsers()
    {
        return $this->hasMany('App\Models\RoleUser', 'roles_id', 'id');
    }

}

