<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the role_users table
 *
 * automatically generated by ModelGenerator.php
 */
class RoleUser extends Model
{
 /**
 * The table associated with the model RoleUser
 *
 * @var string
 */
    protected $table = 'role_users';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\Role model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function roles()
    {
        return $this->belongsTo('App\Models\Role', 'roles_id', 'id');
    }

    /**
    * Relationship with the App\Models\User model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function users()
    {
        return $this->belongsTo('App\Models\User', 'users_id', 'id');
    }

}

