<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the service_providers table
 *
 * automatically generated by ModelGenerator.php
 */
class ServiceProvider extends Model
{
 /**
 * The table associated with the model ServiceProvider
 *
 * @var string
 */
    protected $table = 'service_providers';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['provider', 'description'];

    /**
    * Relationship with the App\Models\CompanySocialMedia model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function companySocialMedia()
    {
        return $this->hasMany('App\Models\CompanySocialMedia', 'service_providers_id', 'id');
    }

    /**
    * Relationship with the App\Models\UserServiceProvider model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function userServiceProviders()
    {
        return $this->hasMany('App\Models\UserServiceProvider', 'service_providers_id', 'id');
    }

}

