<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the shipping_eta table
 *
 * automatically generated by ModelGenerator.php
 */
class ShippingEtum extends Model
{
 /**
 * The table associated with the model ShippingEtum
 *
 * @var string
 */
    protected $table = 'shipping_eta';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['price'];

    /**
    * Relationship with the App\Models\Shipment model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function shipments()
    {
        return $this->hasMany('App\Models\Shipment', 'shipping_eta_id', 'id');
    }

    /**
    * Relationship with the App\Models\ShippingEtaTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function shippingEtaTranslations()
    {
        return $this->hasMany('App\Models\ShippingEtaTranslation', 'shipping_eta_id', 'id');
    }

}

