<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the shipping_methods table
 *
 * automatically generated by ModelGenerator.php
 */
class ShippingMethod extends Model
{
 /**
 * The table associated with the model ShippingMethod
 *
 * @var string
 */
    protected $table = 'shipping_methods';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['method'];

    /**
    * Relationship with the App\Models\Shipment model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function shipments()
    {
        return $this->hasMany('App\Models\Shipment', 'shipping_methods_id', 'id');
    }

    /**
    * Relationship with the App\Models\ShippingEtum model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function shippingEta()
    {
        return $this->hasMany('App\Models\ShippingEtum', 'shipping_methods_id', 'id');
    }

}

