<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the shipments table
 *
 * automatically generated by ModelGenerator.php
 */
class Shipment extends Model
{
 /**
 * The table associated with the model Shipment
 *
 * @var string
 */
    protected $table = 'shipments';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['tracking_id'];

    /**
    * Relationship with the App\Models\CustomerAddress model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function customerAddresses()
    {
        return $this->belongsTo('App\Models\CustomerAddress', 'customer_addresses_id', 'id');
    }

    /**
    * Relationship with the App\Models\Order model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function orders()
    {
        return $this->belongsTo('App\Models\Order', 'orders_id', 'id');
    }

    /**
    * Relationship with the App\Models\ShippingEtum model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function shippingEta()
    {
        return $this->belongsTo('App\Models\ShippingEtum', 'shipping_eta_id', 'id');
    }

    /**
    * Relationship with the App\Models\ShippingStatus model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function shippingStatus()
    {
        return $this->belongsTo('App\Models\ShippingStatus', 'shipping_status_id', 'id');
    }

}

