<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the shippers table
 *
 * automatically generated by ModelGenerator.php
 */
class Shipper extends Model
{
 /**
 * The table associated with the model Shipper
 *
 * @var string
 */
    protected $table = 'shippers';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['name', 'company_name', 'email', 'phone', 'is_active'];

    /**
    * Relationship with the App\Models\Address model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function addresses()
    {
        return $this->belongsTo('App\Models\Address', 'addresses_id', 'id');
    }

}

