<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the models table
 *
 * automatically generated by ModelGenerator.php
 */
class ShippingEta extends Model
{
    protected $table="shipping_eta";
    protected $fillable = ['price'];

    public function ShippingEtaTranslations()
    {
        return $this->hasMany('App\Models\ShippingEtaTranslation', 'shipping_eta_id', 'id');
    }
}

