<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the sizes table
 *
 * automatically generated by ModelGenerator.php
 */
class Size extends Model
{
 /**
 * The table associated with the model Size
 *
 * @var string
 */
    protected $table = 'sizes';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['size'];

    /**
    * Relationship with the App\Models\Cart model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function carts()
    {
        return $this->hasMany('App\Models\Cart', 'sizes_id', 'id');
    }

    /**
    * Relationship with the App\Models\OrderProduct model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function orderProducts()
    {
        return $this->hasMany('App\Models\OrderProduct', 'sizes_id', 'id');
    }

    /**
    * Relationship with the App\Models\ProductSize model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function productSizes()
    {
        return $this->hasMany('App\Models\ProductSize', 'sizes_id', 'id');
    }

    /**
    * Relationship with the App\Models\SizesGuide model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function sizesGuides()
    {
        return $this->hasMany('App\Models\SizesGuide', 'sizes_id', 'id');
    }

}

