<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the sizes_guides_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class SizesGuidesTranslation extends Model
{
 /**
 * The table associated with the model SizesGuidesTranslation
 *
 * @var string
 */
    protected $table = 'sizes_guides_translations';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['shirt_length', 'chest_width', 'sleeve_length'];

    /**
    * Relationship with the App\Models\Lang model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function langs()
    {
        return $this->belongsTo('App\Models\Lang', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\SizesGuide model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function sizesGuides()
    {
        return $this->belongsTo('App\Models\SizesGuide', 'sizes_guides_id', 'id');
    }

}

