<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the sizes_table_has_sizes table
 *
 * automatically generated by ModelGenerator.php
 */
class SizesTableHasSize extends Model
{
 /**
 * The table associated with the model SizesTableHasSize
 *
 * @var string
 */
    protected $table = 'sizes_table_has_sizes';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['shirt_length_in', 'shirt_length_cm', 'chest_width_in', 'chest_width_cm', 'sleeve_length_in',
        'sleeve_length_cm'];

    /**
    * Relationship with the App\Models\Size model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function sizes()
    {
        return $this->belongsTo('App\Models\Size', 'sizes_id', 'id');
    }

    /**
    * Relationship with the App\Models\SizesTable model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function sizesTable()
    {
        return $this->belongsTo('App\Models\SizesTable', 'sizes_table_id', 'id');
    }

}

