<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the sponsors table
 *
 * automatically generated by ModelGenerator.php
 */
class Sponsor extends Model
{
 /**
 * The table associated with the model Sponsor
 *
 * @var string
 */
    protected $table = 'sponsors';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['email', 'phone_number', 'site'];

    /**
    * Relationship with the App\Models\Person model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function people()
    {
        return $this->belongsTo('App\Models\Person', 'people_id', 'id');
    }

    /**
    * Relationship with the App\Models\Ad model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function ads()
    {
        return $this->hasMany('App\Models\Ad', 'sponsors_id', 'id');
    }

}

