<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the staffs table
 *
 * automatically generated by ModelGenerator.php
 */
class Staff extends Model
{
 /**
 * The table associated with the model Staff
 *
 * @var string
 */
    protected $table = 'staffs';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['display_name'];

    /**
    * Relationship with the App\Models\User model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function users()
    {
        return $this->belongsTo('App\Models\User', 'users_id', 'id');
    }

    /**
    * Relationship with the App\Models\StaffReport model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function staffReports()
    {
        return $this->hasMany('App\Models\StaffReport', 'staffs_id', 'id');
    }

}

