<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the staff_reports table
 *
 * automatically generated by ModelGenerator.php
 */
class StaffReport extends Model
{
 /**
 * The table associated with the model StaffReport
 *
 * @var string
 */
    protected $table = 'staff_reports';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['file_url'];

    /**
    * Relationship with the App\Models\Report model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function reports()
    {
        return $this->belongsTo('App\Models\Report', 'reports_id', 'id');
    }

    /**
    * Relationship with the App\Models\Staff model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function staffs()
    {
        return $this->belongsTo('App\Models\Staff', 'staffs_id', 'id');
    }

}

