<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the style_resources table
 *
 * automatically generated by ModelGenerator.php
 */
class StyleResource extends Model
{
 /**
 * The table associated with the model StyleResource
 *
 * @var string
 */
    protected $table = 'style_resources';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['image_url'];

    /**
    * Relationship with the App\Models\ProductStyle model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function productStyles()
    {
        return $this->belongsTo('App\Models\ProductStyle', 'product_styles_id', 'id');
    }

}

