<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the suppliers table
 *
 * automatically generated by ModelGenerator.php
 */
class Supplier extends Model
{
 /**
 * The table associated with the model Supplier
 *
 * @var string
 */
    protected $table = 'suppliers';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['supplier', 'rfc', 'email', 'phone', 'is_active'];

    /**
    * Relationship with the App\Models\SuppliersProduct model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function suppliersProducts()
    {
        return $this->hasMany('App\Models\SuppliersProduct', 'suppliers_id', 'id');
    }

    /**
    * Relationship with the App\Models\SuppliersUser model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function suppliersUsers()
    {
        return $this->hasMany('App\Models\SuppliersUser', 'suppliers_id', 'id');
    }

}

