<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the suppliers_users table
 *
 * automatically generated by ModelGenerator.php
 */
class SuppliersUser extends Model
{
 /**
 * The table associated with the model SuppliersUser
 *
 * @var string
 */
    protected $table = 'suppliers_users';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\Supplier model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function suppliers()
    {
        return $this->belongsTo('App\Models\Supplier', 'suppliers_id', 'id');
    }

    /**
    * Relationship with the App\Models\User model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function users()
    {
        return $this->belongsTo('App\Models\User', 'users_id', 'id');
    }

}

