<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the suppliers_products table
 *
 * automatically generated by ModelGenerator.php
 */
class SuppliersProduct extends Model
{
 /**
 * The table associated with the model SuppliersProduct
 *
 * @var string
 */
    protected $table = 'suppliers_products';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\Product model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function products()
    {
        return $this->belongsTo('App\Models\Product', 'products_id', 'id');
    }

    /**
    * Relationship with the App\Models\Supplier model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function suppliers()
    {
        return $this->belongsTo('App\Models\Supplier', 'suppliers_id', 'id');
    }

}

