<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the term_condition_translations table
 *
 * automatically generated by ModelGenerator.php
 */
class TermConditionTranslation extends Model
{
 /**
 * The table associated with the model TermConditionTranslation
 *
 * @var string
 */
    protected $table = 'term_condition_translations';

 /**
 * Indicates if the model should be timestamped.
 *
 * @var bool
 */
    public $timestamps = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['terms_and_conditions'];

    /**
    * Relationship with the App\Models\Lang model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function langs()
    {
        return $this->belongsTo('App\Models\Lang', 'langs_id', 'id');
    }

    /**
    * Relationship with the App\Models\TermsCondition model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function termsConditions()
    {
        return $this->belongsTo('App\Models\TermsCondition', 'terms_conditions_id', 'id');
    }

}

