<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the terms_conditions table
 *
 * automatically generated by ModelGenerator.php
 */
class TermsCondition extends Model
{
 /**
 * The table associated with the model TermsCondition
 *
 * @var string
 */
    protected $table = 'terms_conditions';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['is_active'];

    /**
    * Relationship with the App\Models\Company model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function companies()
    {
        return $this->hasMany('App\Models\Company', 'terms_conditions_id', 'id');
    }

    /**
    * Relationship with the App\Models\TermConditionTranslation model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\hasMany
    */ 
    public function termConditionTranslations()
    {
        return $this->hasMany('App\Models\TermConditionTranslation', 'terms_conditions_id', 'id');
    }

}

