<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the users_refunds table
 *
 * automatically generated by ModelGenerator.php
 */
class UsersRefund extends Model
{
 /**
 * The table associated with the model UsersRefund
 *
 * @var string
 */
    protected $table = 'users_refunds';

    public $primaryKey = '';

    public $incrementing = false;

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = [];

    /**
    * Relationship with the App\Models\Refund model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function refunds()
    {
        return $this->belongsTo('App\Models\Refund', 'refunds_id', 'id');
    }

    /**
    * Relationship with the App\Models\User model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function users()
    {
        return $this->belongsTo('App\Models\User', 'users_id', 'id');
    }

}

