<?php 
 namespace App\Models;

use Illuminate\Database\Eloquent\Model;
/**
 * Eloquent class to describe the user_service_providers table
 *
 * automatically generated by ModelGenerator.php
 */
class UserServiceProvider extends Model
{
 /**
 * The table associated with the model UserServiceProvider
 *
 * @var string
 */
    protected $table = 'user_service_providers';

 /**
 * The attributes that are mass assignable.
 *
 * @var array
 */
    protected $fillable = ['client_id', 'access_token'];

    /**
    * Relationship with the App\Models\ServiceProvider model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function serviceProviders()
    {
        return $this->belongsTo('App\Models\ServiceProvider', 'service_providers_id', 'id');
    }

    /**
    * Relationship with the App\Models\User model.
    * 
    * @return    Illuminate\Database\Eloquent\Relations\belongsTo
    */ 
    public function users()
    {
        return $this->belongsTo('App\Models\User', 'users_id', 'id');
    }

}

